# Generated by Django 3.2.11 on 2022-01-06 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Chennai', 'Chennai'), ('banglore', 'Banglore'), ('Kolkata', 'Kolkata')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
