# Generated by Django 3.2.11 on 2022-01-06 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_mail_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
