# Generated by Django 3.2.11 on 2022-01-07 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_alter_mail_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='mail',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 12, 49, 23, 21506)),
        ),
    ]
